#!/bin/bash

set -exuo pipefail

FINAL_VERSION=`cat rc-version/version`

root_dir=${PWD}
OUTPUT_DIR=${root_dir}/cf-routing-bosh-release
mkdir -p $OUTPUT_DIR

set +x
if [[ -z "${GCP_BLOBSTORE_SERVICE_ACCOUNT_KEY}" ]]; then
cat > ${root_dir}/${CF_ROUTING_RELEASE_RC_DIR}/config/private.yml <<EOF
---
blobstore:
  options:
    secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
    access_key_id: "${AWS_ACCESS_KEY_ID}"
EOF
fi

if [[ -z ${AWS_ACCESS_KEY_ID} ]]; then
FORMATTED_KEY="$(sed 's/^/      /' <(echo ${GCP_BLOBSTORE_SERVICE_ACCOUNT_KEY}))"
cat > ${root_dir}/${CF_ROUTING_RELEASE_RC_DIR}/config/private.yml <<EOF
---
blobstore:
  options:
    credentials_source: static
    json_key: |
${FORMATTED_KEY}
EOF
fi
set -x

pushd "${CF_ROUTING_RELEASE_RC_DIR}"
  echo "----- Set git identity"
  git config user.email "cf-routing-eng@pivotal.io"
  git config user.name "Routing CI (Automated)"

  git remote add -f master-repo ../routing-release-master
  git merge "master-repo/master" -m 'Merge with master'

  git status
  git diff-index --quiet HEAD -- || ( echo "There are uncommitted changes! Investigate immediately." && exit 1 )

  echo "----- Create final release"
  bosh -v
  bosh -n create-release --sha2 --final --version=${FINAL_VERSION} --tarball=${OUTPUT_DIR}/routing-${FINAL_VERSION}.tgz

  echo "----- Update master and develop branches on origin"

  git add .final_builds releases
  git commit -m "Create final release ${FINAL_VERSION}"

  echo "----- DEBUG: show the commit we just created"
  git --no-pager show HEAD

  cp -a ./  ${root_dir}/routing-release-final/
popd
