#!/bin/bash
set -eu -o pipefail

if [[ -f networking-oss-tools/scripts/script_helpers.sh ]]; then
  source networking-oss-tools/scripts/script_helpers.sh
else
  source routing-release-ci/ci/scripts/script_helpers.sh
fi

bosh_login "${ENVIRONMENT}"

credhub set -n "${NAME}" -t password -w "${VALUE}" &> /dev/null
