#!/bin/bash

set -e

RUN_DIR=/var/vcap/sys/run/router_configurer
LOG_DIR=/var/vcap/sys/log/router_configurer

function create_directories() {
    mkdir -p $RUN_DIR
    chown -R vcap:vcap $RUN_DIR

    mkdir -p $LOG_DIR
    chown -R vcap:vcap $LOG_DIR
}

function setcap_haproxy() {
    PATH=/var/vcap/packages/haproxy/bin:/var/vcap/packages/haproxy-monitor/bin:$PATH
    DAEMON=$(which haproxy)
    setcap cap_net_bind_service,cap_sys_resource=+ep $DAEMON
}

create_directories
setcap_haproxy

exit 0
