#!/bin/bash

set -e

RUN_DIR=/var/vcap/sys/run/router_configurer
LOG_DIR=/var/vcap/sys/log/router_configurer

function create_directories() {
    mkdir -p $RUN_DIR
    chown -R vcap:vcap $RUN_DIR

    mkdir -p $LOG_DIR
    chown -R vcap:vcap $LOG_DIR
}

create_directories

exit 0
