#!/bin/bash

set -e -x -u

export GEM_HOME="${HOME}/.gem"
mkdir -p "${GEM_HOME}"

root_dir=${PWD}
CF_RELEASE_DIR="${root_dir}/${CF_RELEASE_DIR:?"\$CF_RELEASE_DIR not set"}"

OUTPUT_DIR=${root_dir}/cf-release-tarball
mkdir -p $OUTPUT_DIR

VERSION=$(cat version/version)

pushd "${CF_RELEASE_DIR}"
  echo "----- Create dev release"
  SHA=$(git rev-parse --short HEAD)
  version=$VERSION.+$SHA

  bosh -v
  bosh --parallel 4 -n create release --version ${version} --with-tarball

  mv dev_releases/cf/*.tgz ${OUTPUT_DIR}/cf-dev-release.tgz
popd
