// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"code.cloudfoundry.org/routing-release/cf-tcp-router/metrics_reporter"
)

type FakeMetricsEmitter struct {
	EmitStub        func(*metrics_reporter.MetricsReport)
	emitMutex       sync.RWMutex
	emitArgsForCall []struct {
		arg1 *metrics_reporter.MetricsReport
	}
}

func (fake *FakeMetricsEmitter) Emit(arg1 *metrics_reporter.MetricsReport) {
	fake.emitMutex.Lock()
	fake.emitArgsForCall = append(fake.emitArgsForCall, struct {
		arg1 *metrics_reporter.MetricsReport
	}{arg1})
	fake.emitMutex.Unlock()
	if fake.EmitStub != nil {
		fake.EmitStub(arg1)
	}
}

func (fake *FakeMetricsEmitter) EmitCallCount() int {
	fake.emitMutex.RLock()
	defer fake.emitMutex.RUnlock()
	return len(fake.emitArgsForCall)
}

func (fake *FakeMetricsEmitter) EmitArgsForCall(i int) *metrics_reporter.MetricsReport {
	fake.emitMutex.RLock()
	defer fake.emitMutex.RUnlock()
	return fake.emitArgsForCall[i].arg1
}

var _ metrics_reporter.MetricsEmitter = new(FakeMetricsEmitter)
