#!/bin/bash
set -e -x

source ~/.bashrc

if [ -n "$LOGS_DIR" ]; then
  mkdir $LOGS_DIR
fi

mkdir -p ${PWD}/${OUTPUT_DIR}

num_runs=${NUMBER_OF_RUNS:-1}

bosh -n -t $BOSH_DIRECTOR download manifest $BOSH_DEPLOYMENT > /tmp/deployment.yml

sed -i -e "1d" /tmp/deployment.yml

for ((i=0; i<${num_runs}; i++)); do
  bosh -n --color -t $BOSH_DIRECTOR -d /tmp/deployment.yml $COMMAND > ${PWD}/${OUTPUT_DIR}/output
done
