#!/bin/bash
set -euo pipefail

FORMATTED_KEY="$(sed 's/^/      /' <(echo $GCP_BLOBSTORE_SERVICE_ACCOUNT_KEY))"
cat > $PWD/istio-release/config/private.yml <<EOF
---
blobstore:
  options:
    credentials_source: static
    json_key: |
$FORMATTED_KEY
EOF

pushd grpcurl-source
  new_grpcurl_version="$(git rev-parse HEAD)"
popd

pushd istio-release
  bosh2 sync-blobs
  old_grpcurl_version=$(ls -1 blobs/grpcurl-linux/grpcurl-* | xargs basename | sed 's/grpcurl-\(.*\)/\1/g')

  bosh2 remove-blob grpcurl-linux/grpcurl-${old_grpcurl_version}
  bosh2 add-blob ../grpcurl-bin/grpcurl grpcurl-linux/grpcurl-${new_grpcurl_version}
  sed -i "s/grpcurl-linux\/grpcurl-[a-zA-Z0-9]*/grpcurl-linux\/grpcurl-${new_grpcurl_version}/g" packages/grpcurl/*
  bosh2 blobs
  bosh2 upload-blobs
  bosh2 blobs

  git --no-pager diff config/ packages/
  git add config/blobs.yml packages/grpcurl
  git config user.email "cf-routing-eng@pivotal.io"
  git config user.name "Routing CI (Automated)"
  git commit -m "Update grpcurl blob"
  cp -a ./ ../updated-istio-release/
popd
