#!/bin/bash
set -ex -o pipefail

source networking-oss-deployments/scripts/script_helpers.sh
source routing-release-ci/ci/tasks/shared-functions
set_env_vars

ENVIRONMENT="${ENVIRONMENT:?"ENVIRONMENT not set"}"
set +x
  bosh_login_toolsmiths "${ENVIRONMENT}"
set -x

ZERODOWNTIME_DEPLOYMENT=$(mktemp -t zero_downtime.XXXX.yml)

cat <<EOF >> "${ZERODOWNTIME_DEPLOYMENT}"
---
name: zero-downtime
addons:
- include:
    stemcell:
    - os: ubuntu-jammy
  jobs:
  - name: bpm
    release: bpm
  name: bpm
- name: bosh-dns-aliases
  jobs:
  - name: bosh-dns-aliases
    release: bosh-dns-aliases
    properties:
      aliases:
      - domain: nats.service.cf.internal
        targets:
        - query: '*'
          instance_group: nats
          deployment: cf
          network: default
          domain: bosh
      - domain: _.nats.service.cf.internal
        targets:
        - query: '_'
          instance_group: nats
          deployment: cf
          network: default
          domain: bosh
update:
  canaries: 1
  canary_watch_time: 10000-300000
  max_in_flight: 5
  serial: false
  update_watch_time: 10000-300000
instance_groups:
- name: drroute_tcp_zero_downtime
  azs:
  - z1
  instances: 1
  vm_type: f1-micro
  stemcell: default
  update:
    max_in_flight: 1
    serial: true
  networks:
  - name: default
  jobs:
  - name: drroute
    release: zero-downtime
  - name: route_registrar
    release: routing
    consumes:
      nats-tls: {from: nats-tls, deployment: cf}
    properties:
      nats:
        tls:
          enabled: true
          client_cert: "((/bosh-${ENVIRONMENT}/cf/nats_client_cert.certificate))"
          client_key: "((/bosh-${ENVIRONMENT}/cf/nats_client_cert.private_key))"
      route_registrar:
        routing_api:
          enabled_api_endpoints: "both"
          server_ca_cert: ((/bosh-${ENVIRONMENT}/cf/routing_api_tls_client.ca))
          client_cert: ((/bosh-${ENVIRONMENT}/cf/routing_api_tls_client.certificate))
          client_private_key: ((/bosh-${ENVIRONMENT}/cf/routing_api_tls_client.private_key))
        routes:
        - name: drroute
          port: 8080
          registration_interval: 20s
          tags:
            component: drroute
          uris:
          - "drroute_zero_downtime_tcp_release.${ENVIRONMENT}.cf-app.com"
- name: drroute_zero_downtime
  azs:
  - z1
  instances: 1
  vm_type: f1-micro
  stemcell: default
  update:
    max_in_flight: 1
    serial: true
  networks:
  - name: default
  jobs:
  - name: drroute
    release: zero-downtime
  - name: route_registrar
    release: routing
    consumes:
      nats-tls: {from: nats-tls, deployment: cf}
    properties:
      nats:
        tls:
          enabled: true
          client_cert: "((/bosh-${ENVIRONMENT}/cf/nats_client_cert.certificate))"
          client_key: "((/bosh-${ENVIRONMENT}/cf/nats_client_cert.private_key))"
      route_registrar:
        routing_api:
          enabled_api_endpoints: "both"
          server_ca_cert: ((/bosh-${ENVIRONMENT}/cf/routing_api_tls_client.ca))
          client_cert: ((/bosh-${ENVIRONMENT}/cf/routing_api_tls_client.certificate))
          client_private_key: ((/bosh-${ENVIRONMENT}/cf/routing_api_tls_client.private_key))
        routes:
        - name: drroute
          port: 8080
          registration_interval: 20s
          tags:
            component: drroute
          uris:
          - "drroute_zero_downtime_release.${ENVIRONMENT}.cf-app.com"
releases:
- name: bpm
  version: latest
- name: bosh-dns-aliases
  version: latest
- name: routing
  version: latest
- name: zero-downtime
  version: latest
stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest
EOF

function cleanup() {
  pkill ssh || true
}
trap 'cleanup' EXIT

pushd zero-downtime-release
  bosh create-release
  bosh -e "${ENVIRONMENT}" upload-release --fix --rebase
  bosh -e "${ENVIRONMENT}" -d zero-downtime -n deploy "${ZERODOWNTIME_DEPLOYMENT}"
popd
