#!/bin/bash

set -e -x -u -o pipefail

cp -R cf-deployment/operations/* merged-operations/
cp -R routing-release-ci/ci/opsfiles/* merged-operations/

if [ -d source1 ]; then
  cp -R source1/${SOURCE1_DIR:-""}/* merged-operations/
fi

if [ -d source2 ]; then
  cp -R source2/${SOURCE2_DIR:-""}/* merged-operations/
fi

if [ -d cf-networking-opsfiles ]; then
    cp -R cf-networking-opsfiles/ci/opsfiles/use-cf-networking-2-for-istio-release.yml merged-operations/
fi
