#!/bin/bash
set -e -x -u -o pipefail

indir=./bbl-state
outdir=./updated-bbl-state
git clone "${indir}" "${outdir}"

function set_git_config() {
  git config user.name "${GIT_COMMIT_USERNAME}"
  git config user.email "${GIT_COMMIT_EMAIL}"
}

function commit() {
  local git_root_dir
  git_root_dir="${1}"
  local commit_message
  commit_message="${2}"

  pushd "${git_root_dir}"
    if [[ -n $(git status --porcelain) ]]; then
    set_git_config
    git add .
    git commit -m "${commit_message}"
  fi
}

gimme_certs() {
    local common_name;
    common_name="${1:-fake}";
    local ca_common_name;
    ca_common_name="${2:-${common_name}_ca}";
    local depot_path;
    depot_path="${3:-fake_cert_stuff}";
    certstrap --depot-path "${depot_path}" init --common-name "${ca_common_name}" --passphrase ""
    certstrap --depot-path "${depot_path}" request-cert --common-name "${common_name}" --passphrase ""
    certstrap --depot-path "${depot_path}" sign --CA "${ca_common_name}" --passphrase "" "${common_name}"
}

lb_certs="${outdir}/${ENVIRONMENT}/lb_certs"

if ! [[ -a "${lb_certs}/key.pem" ]]; then
  gimme_certs "${ENVIRONMENT}" fakeCA /tmp

  mkdir -p "$lb_certs"

  cp "/tmp/${ENVIRONMENT}.key" "${lb_certs}/key.pem"
  cp "/tmp/${ENVIRONMENT}.crt" "${lb_certs}/cert.pem"

  commit "${outdir}" "${GIT_COMMIT_MSG}"
fi
