#!/bin/bash

set -e -x -u

export GEM_HOME="${HOME}/.gem"
mkdir -p "${GEM_HOME}"

root_dir=${PWD}
ROUTING_PERF_RELEASE_DIR="${root_dir}/${ROUTING_PERF_RELEASE_DIR:?"\$ROUTING_PERF_RELEASE_DIR not set"}"

OUTPUT_DIR=${root_dir}/routing-perf-release-tarball
mkdir -p $OUTPUT_DIR

pushd "${ROUTING_PERF_RELEASE_DIR}"
  echo "----- Create dev release"
  git_describe_output=$(git describe --long --tags)
  # major &minor represents last final release version
  major=$(echo "${git_describe_output}" | cut -f1 -d- | cut -c -5)
  #patch represents the git sha
  minor=$(echo "$git_describe_output}" | cut -f2 -d-)
  patch=$(echo "${git_describe_output}" | cut -f3 -d-)
  NEW_VERSION=${major}.${minor}+${patch}

  bosh -v
  bosh --parallel 4 -n create release --name routing-perf --version ${NEW_VERSION} --with-tarball

  mv dev_releases/routing-perf/*.tgz ${OUTPUT_DIR}/routing-perf-release.tgz
popd
