#!/bin/bash

set -e -x -u -o pipefail

ENV_NAME=$(cat env-name/name)
TEMPLATE_FILE='routing-release-ci/ci/tasks/update-smoke-tests-ops-file/smoke_tests.yml.erb'
OUTPUT_FILE='smoke-tests-ops-file/smoke_tests.yml'

erb environment_name="${ENV_NAME}" "${TEMPLATE_FILE}" > "${OUTPUT_FILE}"

