#!/bin/bash

set -euxo pipefail

env_dir=${HOME}/workspace/deployments-routing/lite
cf_deployment_dir=${HOME}/workspace/cf-deployment
bosh_deployment_dir=${HOME}/workspace/bosh-deployment
routing_ci_dir=${HOME}/workspace/routing-release-ci/ci

source $routing_ci_dir/scripts/script_helpers.sh

pushd "${bosh_deployment_dir}"
  echo "updating bosh-deployment..."
  git pull
popd

pushd "${cf_deployment_dir}"
  echo "updating cf-deployment..."
  git pull
popd

bosh create-env ${bosh_deployment_dir}/bosh.yml \
--state $env_dir/state.json \
-o ${bosh_deployment_dir}/virtualbox/cpi.yml \
-o ${bosh_deployment_dir}/virtualbox/outbound-network.yml \
-o ${bosh_deployment_dir}/bosh-lite.yml \
-o ${bosh_deployment_dir}/bosh-lite-runc.yml \
-o ${bosh_deployment_dir}/uaa.yml \
-o ${bosh_deployment_dir}/credhub.yml \
-o ${bosh_deployment_dir}/jumpbox-user.yml \
--vars-store $env_dir/bosh-vars.yml \
-v director_name="bosh-lite" \
-v internal_ip=192.168.50.6 \
-v internal_gw=192.168.50.1 \
-v internal_cidr=192.168.50.0/24 \
-v outbound_network_name="NatNetwork"

bosh_login lite

bosh -e 192.168.50.6 --ca-cert <(bosh int $env_dir/bosh-vars.yml --path /director_ssl/ca) alias-env vbox

bosh -e vbox -n update-cloud-config "${cf_deployment_dir}/iaas-support/bosh-lite/cloud-config.yml"
# bosh -e vbox -n update-cloud-config "${bosh_deployment_dir}/warden/cloud-config.yml"

STEMCELL_VERSION="$(bosh int ${cf_deployment_dir}/cf-deployment.yml --path=/stemcells/0/version)"
echo "will upload stemcell ${STEMCELL_VERSION}"
bosh -e vbox upload-stemcell "https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-xenial-go_agent?v=${STEMCELL_VERSION}"

# mac specific
sudo route add -net "10.244.0.0/16" "192.168.50.6"
