#!/bin/bash
set -e

function usage() {
  >&2 echo "    Usage:
    $0 /path/to/cf-release-manifest

    Ex:
    $0 ~/deployments/bosh-lite/cf.yml
"
  exit 1
}

cf_manifest_file=$1

if [ ! -z "$2" ]; then
  >&2 echo "Too many arguments"
  usage
fi

if [ ! -f "${cf_manifest_file}" ]; then
  >&2 echo "CF release manifest ${cf_manifest_file} does not exist"
  usage
fi

root_dir=$(dirname $0)

mkdir -p ${root_dir}/manifests

${root_dir}/../scripts/generate-manifest ${root_dir}/stubs ${cf_manifest_file}> ${root_dir}/manifests/cf-routing-manifest.yml

bosh deployment ${root_dir}/manifests/cf-routing-manifest.yml