#!/bin/bash

set -e -u

root_dir=$(dirname $0)
mkdir -p ${root_dir}/manifests

director_uuid=/tmp/director.yml
printf "director_uuid: %s" $(bosh status --uuid) > ${director_uuid}

acceptance_tests_manifest=${root_dir}/stubs/router-acceptance-tests.yml

spiff merge \
  ${acceptance_tests_manifest} \
  ${director_uuid} \
  > ${root_dir}/manifests/router-acceptance-test-deployment.yml

bosh deployment ${root_dir}/manifests/router-acceptance-test-deployment.yml
bosh -n deploy

set +e
bosh run errand router_acceptance_tests --download-logs --keep-alive
errand_result=$?
set -e

original_name=$(ls router_acceptance_tests.0.*.tgz)
new_name=$(echo $original_name | sed 's/\.0\./\.0.0.0./')
mv $original_name $new_name
exit $errand_result
