#!/bin/bash
set -e

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc

set -u

root_dir="${PWD}"

# Inputs
ROUTING_RELEASE_DIR="${root_dir}/${ROUTING_RELEASE_DIR:?"ROUTING_RELEASE_DIR must be provided"}"
OUTPUT_DIR="${root_dir}/${OUTPUT_DIR:?"OUTPUT_DIR must be provided"}"

main() {
  pushd $ROUTING_RELEASE_DIR
    sha=$(git rev-parse HEAD)
  popd

  sed -i'' "s/ROUTING_RELEASE_VERSION/$sha/g" $MANIFEST_PATH

  echo "=============  MANIFEST  ====================="
  cat $MANIFEST_PATH

  cp $MANIFEST_PATH $OUTPUT_DIR/.
}

main
