#!/bin/bash
set -e -o pipefail

: "${ENVIRONMENT:?"ENVIRONMENT not set"}"
: "${SSH_DESTINATION_CIDR:=10.0.0.0/8}"

# shellcheck disable=SC1091
if [[ -f networking-oss-tools/scripts/script_helpers.sh ]]; then
  source networking-oss-tools/scripts/script_helpers.sh
else
  source routing-release-ci/ci/scripts/script_helpers.sh
fi

function set_git_config() {
  git config user.name "${GIT_COMMIT_USERNAME}"
  git config user.email "${GIT_COMMIT_EMAIL}"
}

bosh_login "${ENVIRONMENT}"

cf_deployment_name="${BOSH_DEPLOYMENT}"
cf_admin_username="admin"
cf_admin_password=$(extract_var "${ENVIRONMENT}" cf_admin_password)
bosh_environment="${BOSH_ENVIRONMENT}"
bosh_client="${BOSH_CLIENT}"
bosh_client_secret="${BOSH_CLIENT_SECRET}"
bosh_ca_cert="${BOSH_CA_CERT}"
ssh_proxy_cidr="${SSH_DESTINATION_CIDR}"
ssh_proxy_user="${BOSH_GW_USER}"


pushd "${ENV_PATH}/bbl-state"
  bbl version
  cf_api_url="https://api.$(jq .lb.domain bbl-state.json -r)"
  ssh_proxy_host="$(bbl jumpbox-address)"
  ssh_proxy_private_key="$(bbl ssh-key)"
popd

integration_config="{}"
string_vars="cf_api_url cf_deployment_name cf_admin_username cf_admin_password bosh_environment bosh_client bosh_client_secret bosh_ca_cert ssh_proxy_cidr ssh_proxy_user ssh_proxy_host ssh_proxy_private_key"
for var in $string_vars
do
  integration_config=$(echo ${integration_config} | jq ".${var}=\"${!var}\"")
done

integration_config=$(echo ${integration_config} | jq '.["include_cf-routing"]=true')

mkdir -p created-drats-config
pushd "created-drats-config"
  echo "$integration_config" > "drats_integration_config.json"

  set_git_config
  git add "drats_integration_config.json"
  git commit -m "creating drats config for ${ENVIRONMENT}"
popd
