#!/bin/bash

set -e -x

cd routing-release/

export GOPATH="${PWD}"
export PATH="${GOPATH}/bin:${PATH}"

go get github.com/nats-io/gnatsd

go install github.com/onsi/ginkgo/ginkgo

chown -R mysql:mysql /var/lib/mysql /var/log/mysql /var/run/mysqld
chown -R postgres:postgres /var/lib/postgresql /var/log/postgresql /var/run/postgresql /etc/postgresql
chown -R root:ssl-cert /etc/ssl/private

service rsyslog restart
service mysql restart
service postgresql restart

./scripts/run-unit-tests "${PACKAGE}"
