#!/usr/bin/env bash
set -e

source networking-oss-deployments/scripts/script_helpers.sh
source routing-release-ci/ci/tasks/shared-functions

set_env_vars
admin_password=$(get_cf_admin_password_toolsmiths "${ENVIRONMENT}")
cf api "api.${CF_APP_DOMAIN}" --skip-ssl-validation
cf auth admin "${admin_password}"
cf target -o "${CF_ORG}" -s "${CF_SPACE}"

# Expects the app to be already present
cf apps | grep "${CF_APP_NAME}" | grep "started"

echo "Starting zero downtime test..."

if [[ "${TCP}" = "true" ]]; then
  TCP_DOMAIN=tcp.${CF_APP_DOMAIN}
  TCP_PORT=$(cf routes | grep ${TCP_DOMAIN}| awk '{print $3}')
  POLL_URL="${TCP_DOMAIN}:${TCP_PORT}"
else
  POLL_URL="${APP_URL}/health"
fi

curl -vvv "${APP_URL}/start" -d'{"Endpoint":"'${POLL_URL}'"}'
