#!/usr/bin/env bash
set -e

source networking-oss-deployments/scripts/script_helpers.sh

cf_login "${ENVIRONMENT}"
cf target -o "${CF_ORG}" -s "${CF_SPACE}"

if [[ "${TCP}" = "true" ]]; then
  TCP_DOMAIN="tcp.${CF_APP_DOMAIN}"
  set +e
    cf domains | grep "${TCP_DOMAIN}"
    TCP_DOMAIN_CHECK=$?
  set -e
  # If domain does not exist create new tcp domain
  if [[ ${TCP_DOMAIN_CHECK} != "0" ]]; then
      cf create-shared-domain "${TCP_DOMAIN}" --router-group default-tcp
  fi
fi

set +e
echo "Checking to see if ${CF_APP_NAME} exists..."
cf apps | grep "${CF_APP_NAME}" | grep "started"
APP_CHECK=$?
set -e

# If app does not exist push and map-route
if [ "${APP_CHECK}" != "0" ]; then
  echo "Cloning doctorroute repo"
  git clone https://github.com/cf-routing/doctorroute.git

  pushd doctorroute
    echo "Pushing doctorroute..."
    cf target -o "${CF_ORG}" -s "${CF_SPACE}"
    cf push "${CF_APP_NAME}" -s "cflinuxfs3" --no-route
    cf map-route "${CF_APP_NAME}" "${CF_APP_DOMAIN}" -n "${CF_APP_NAME}"
    if [[ "${TCP}" = "true" ]]; then
      cf map-route "${CF_APP_NAME}" "${TCP_DOMAIN}"
    fi
  popd
fi

