#!/bin/bash
set -ex -o pipefail

if [[ -z "${ENVIRONMENT_NAME}" ]]; then

    URL="https://environments.toolsmiths.cf-app.com/pooled_gcp_engineering_environments/claim?api_token=$TOOLSMITHS_API_TOKEN&pool_name=${ENVIRONMENT_TYPE}&notes=${ENVIRONMENT_NOTES}"

    curl -v -X POST "${URL}" > cf-environment/metadata
else
    URL="https://environments.toolsmiths.cf-app.com/pooled_gcp_engineering_environments/claim?api_token=$TOOLSMITHS_API_TOKEN&environment_name=${ENVIRONMENT_NAME}"

    curl -v ${URL} > cf-environment/metadata
fi

jq -r .name cf-environment/metadata | tee cf-environment/name || \
    { echo 'no environments available, retrying in 30 seconds...'; sleep 30; $0 $@; }

