#!/bin/bash

set -e -x -u

export GEM_HOME="${HOME}/.gem"
mkdir -p "${GEM_HOME}"

pushd cf-release-rc
  echo "----- Create dev release"
  version=$(date "+%s")
  bosh --parallel 4 -n create release --version ${version} --with-tarball

  mv dev_releases/cf/*.tgz ../cf-dev-release.tgz
popd
