#!/bin/bash

set -e -x -u

environment_path="${PWD}/${DEPLOYMENTS_DIR}/router-deployments-runtime/${ENVIRONMENT_NAME}"
stubs_path="${environment_path}/stubs"


pushd router-release

export BOSH_USER=${BOSH_USER}
export BOSH_PASSWORD=${BOSH_PASSWORD}
bosh -n target 192.168.50.4 lite
director_uuid=/tmp/director.yml

printf "director_uuid: %s" $(bosh status --uuid) > ${director_uuid}

spiff merge \
  manifest-generation/router.yml \
  ${stubs_path}/property-overrides.yml \
  ${stubs_path}/instance-count-overrides.yml \
  ${stubs_path}/persistent-disk-overrides.yml \
  ${stubs_path}/iaas-settings.yml \
  > /tmp/router.yml

  spiff merge \
  manifest-generation/misc-templates/bosh.yml \
  ${director_uuid} \
  /tmp/router.yml \
  > ../router-deployment.yml
popd