#!/bin/bash

set -e -x -u

environment_path="${PWD}/${DEPLOYMENTS_DIR}/${ENVIRONMENT}"
stubs_path="${environment_path}/stubs"
templates_path="${environment_path}/templates"

pushd cf-release-rc
  ./generate_deployment_manifest ${INFRASTRUCTURE} ../deployments-routing/${ENVIRONMENT}/stubs/cf/*.yml > ../cf-deployment.yml
popd

pushd diego-release

  cp ../cf-deployment.yml /tmp/cf.yml

  ./scripts/generate-deployment-manifest \
    ${stubs_path}/director-uuid.yml \
    ${stubs_path}/diego/property-overrides.yml \
    ${stubs_path}/diego/instance-count-overrides.yml \
    ${stubs_path}/diego/persistent-disk-overrides.yml \
    ${stubs_path}/diego/aws-iaas-settings.yml \
    ${stubs_path}/diego/additional-jobs.yml \
    /tmp \
    > ../diego-deployment.yml

  echo "===GENERATED MANIFEST==="
  cat ../diego-deployment.yml

popd

