#!/bin/bash

set -e -x -u

environment_path="${PWD}/${DEPLOYMENTS_DIR}/router-deployments-runtime/${ENVIRONMENT_NAME}"
stubs_path="${environment_path}/stubs"


pushd cf-routing-release

export BOSH_USER=${BOSH_USER}
export BOSH_PASSWORD=${BOSH_PASSWORD}
bosh -n target ${BOSH_TARGET}
director_uuid=/tmp/director.yml

printf "director_uuid: %s" $(bosh status --uuid) > ${director_uuid}

spiff merge \
  templates/router.yml \
  ${stubs_path}/property-overrides.yml \
  ${stubs_path}/instance-count-overrides.yml \
  ${stubs_path}/persistent-disk-overrides.yml \
  ${stubs_path}/iaas-settings.yml \
  > /tmp/router.yml

  spiff merge \
  templates/router-deployment.yml \
  ${director_uuid} \
  /tmp/router.yml \
  > ../router-deployment.yml
popd