#!/bin/bash

set -e -x -u

environment_path="${PWD}/deployments-routing/${ENVIRONMENT_NAME}/"
stubs_path="${environment_path}/stubs/routing"
deployments_path="${environment_path}/deployments"
cf_manifest_file="${deployments_path}/cf.yml"

pushd cf-routing-release

export BOSH_USER=${BOSH_USER}
export BOSH_PASSWORD=${BOSH_PASSWORD}
bosh -n target ${BOSH_TARGET}
director_uuid=/tmp/director.yml

printf "director_uuid: %s" $(bosh status --uuid) > ${director_uuid}

spiff merge \
  templates/config-from-cf.yml \
  templates/config-from-cf-internal.yml \
  ${cf_manifest_file} \
  > /tmp/config-from-cf.yml

spiff merge \
  templates/router.yml \
  ${stubs_path}/property-overrides.yml \
  ${stubs_path}/instance-count-overrides.yml \
  ${stubs_path}/persistent-disk-overrides.yml \
  ${stubs_path}/iaas-settings.yml \
  /tmp/config-from-cf.yml \
  > /tmp/router.yml

  spiff merge \
  templates/router-deployment.yml \
  ${director_uuid} \
  /tmp/router.yml \
  > ../router-deployment.yml
popd
