#!/bin/bash

set -e -x -u

pushd cf-routing-release
  echo "----- Set git identity"
  git config user.email "cf-routing-eng@pivotal.io"
  git config user.name "Routing CI (Automated)"

  git merge --no-edit origin/master
popd