#!/bin/bash

set -e -x -u

export BOSH_USER=${BOSH_USER}
export BOSH_PASSWORD=${BOSH_PASSWORD}
bosh -n target ${BOSH_TARGET}

bosh deployment ${ACCEPTANCE_TESTS_MANIFEST}

set +e
bosh run errand router_acceptance_tests --download-logs --keep-alive
errand_result=$?
set -e

original_name=$(ls router_acceptance_tests.0.*.tgz)
new_name=$(echo $original_name | sed 's/\.0\./\.0.0.0./')
mv $original_name $new_name
exit $errand_result