#!/bin/bash
# vim: set ft=sh

set -e

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

cd router-release/

export GOPATH=$PWD
export PATH=$GOPATH/bin:$PATH

go install github.com/onsi/ginkgo/ginkgo

./scripts/run-unit-tests -race "$@"
