#!/bin/bash
set -ex -o pipefail

source routing-release-ci/ci/scripts/script_helpers.sh

ENVIRONMENT="${ENVIRONMENT:?"ENVIRONMENT not set"}"
bosh_login "${ENVIRONMENT}"

function cleanup() {
  pkill ssh || true
}
trap 'cleanup' EXIT

if [ -n "${LOGS_DIR}" ]; then
  mkdir "${LOGS_DIR}"
fi

STEMCELL_PATH="$(ls ${STEMCELL_REGEX})"

export BOSH_DEPLOYMENT="${DEPLOYMENT:-cf}"
bosh -n upload-stemcell "${STEMCELL_PATH}"

IFS=', ' read -r -a array <<< "${RELEASES_DIR}"

for element in ${array[@]}
do
  RELEASE_PATH="$(ls "${element}")"
  bosh -n upload-release "${RELEASE_PATH}"
done

bosh -n deploy "${MANIFEST}"
