#!/bin/bash

set -e -x

source ~/.bashrc

FINAL_VERSION=`cat rc-version/version`
FINAL_RELEASE_TGZ="routing-${FINAL_VERSION}.tgz"

root_dir=${PWD}
RELEASE_DIR=${root_dir}/cf-routing-bosh-release
OUTPUT_DIR=${root_dir}/release-checksum
CHECKSUM_FILE="${OUTPUT_DIR}/${FINAL_RELEASE_TGZ}.sha256"

mkdir -p ${OUTPUT_DIR}

pushd "${RELEASE_DIR}"
  echo "calculating checksum"
  sha256sum "${FINAL_RELEASE_TGZ}" > "${CHECKSUM_FILE}"
  cp "${CHECKSUM_FILE}" .
  sha256sum -c "${FINAL_RELEASE_TGZ}.sha256"
  echo "created sha file at ${CHECKSUM_FILE}"
popd
