#!/usr/bin/env bash

set -eo pipefail

pushd "${PWD}/${VARS_LOCATION}" > /dev/null
  eval "$(bbl print-env)"
  cf_admin_password=$(credhub find -j -n cf_admin_password | jq -r .credentials[].name | xargs credhub get -j -n | jq -r .value)
  wildcard_ca=$(credhub find -j -n envoy_wildcard_ca | jq -r .credentials[].name | xargs credhub get -j -n | jq .value.ca)
popd > /dev/null

gopath_dir="/root/go/src/code.cloudfoundry.org"
mkdir -p "${gopath_dir}"
cp -R istio-acceptance-tests "${gopath_dir}"

go install code.cloudfoundry.org/istio-acceptance-tests/vendor/github.com/onsi/ginkgo/ginkgo

pushd "${gopath_dir}/istio-acceptance-tests"
  cat << EOF > "${PWD}/config.json"
{
  "cf_system_domain": "${CF_LOGIN_DOMAIN}",
  "cf_istio_domain": "${API_DOMAIN}",
  "cf_admin_user": "${CF_ADMIN_USER}",
  "cf_admin_password": "${cf_admin_password}",
  "cf_internal_apps_domain": "${INTERNAL_DOMAIN}",
  "product_page_docker_tag": "${PRODUCT_PAGE_DOCKER_REPO}",
  "reviews_docker_tag": "${REVIEWS_DOCKER_REPO}",
  "ratings_docker_tag": "${RATINGS_DOCKER_REPO}",
  "details_docker_tag": "${DETAILS_DOCKER_REPO}",
  "wildcard_ca": ${wildcard_ca}
}
EOF

  CONFIG="${PWD}/config.json" ginkgo -v -r -failOnPending \
    -randomizeAllSpecs -nodes="${NODES}" -keepGoing
popd
