#!/bin/bash -e

RUN_DIR=/var/vcap/sys/run/gorouter
LOG_DIR=/var/vcap/sys/log/gorouter
PIDFILE=${RUN_DIR}/gorouter.pid

source /var/vcap/packages/routing_utils/pid_utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "gorouter"

    mkdir -p $RUN_DIR
    chown -R vcap:vcap $RUN_DIR
    mkdir -p $LOG_DIR
    chown -R vcap:vcap $LOG_DIR

    setcap cap_net_bind_service=+ep /var/vcap/packages/gorouter/bin/gorouter

    chpst -u vcap:vcap /var/vcap/jobs/gorouter/bin/run_gorouter &
    ;;

  stop)
    /sbin/start-stop-daemon \
      --pidfile "$PIDFILE" \
      --retry TERM/25/KILL \
      --oknodo \
      --stop

      # Note: the --remove-pidfile option is available as of version 1.17.19 of
      # # start-stop-daemon, but Ubuntu stemcells only provide version 1.17.5. Thus we
      # # need to remove the pidfile by ourselves.

      rm $PIDFILE
    ;;

  *)
    echo "Usage: gorouter_ctl {start|stop}"

    ;;

esac
