#!/bin/bash

set -e

scripts_path=./$(dirname $0)
source $scripts_path/get_paths.sh

$scripts_path/generate-bosh-lite-manifest $CF_MANIFESTS_DIR/cf.yml $DIEGO_MANIFESTS_DIR/diego.yml

bosh --parallel 10 sync blobs
bosh create release --force
bosh -t 192.168.50.4 -n upload release
bosh -t 192.168.50.4 -d $ROUTING_MANIFESTS_DIR/routing-manifest.yml -n deploy
bosh -n cleanup
