#!/bin/bash
set -e

function usage() {
  >&2 echo "    Usage:
    $0 /path/to/cf-release-manifest /path/to/diego-release-manifest

    Ex:
    $0 ~/deployments/bosh-lite/cf.yml ~/deployments/bosh-lite/diego.yml
"
  exit 1
}

cf_manifest_file=$1
diego_manifest_file=$2

if [ ! -z "$3" ]; then
  >&2 echo "Too many arguments"
  usage
fi

if [ -z "${cf_manifest_file}" ]; then
  cf_manifest_file=$HOME/workspace/cf-release/bosh-lite/deployments/cf.yml
fi

if [ ! -f "${cf_manifest_file}" ]; then
  >&2 echo "CF release manifest ${cf_manifest_file} does not exist"
  usage
fi

if [ -z "${diego_manifest_file}" ]; then
  diego_manifest_file=$HOME/workspace/diego-release/bosh-lite/deployments/diego.yml
fi

if [ ! -f "${diego_manifest_file}" ]; then
  >&2 echo "Diego release manifest ${diego_manifest_file} does not exist"
  usage
fi

root_dir=$(dirname $0)
bosh_lite_dir=${root_dir}/../bosh-lite

mkdir -p ${bosh_lite_dir}/deployments

${root_dir}/generate-manifest ${bosh_lite_dir}/stubs ${cf_manifest_file} ${diego_manifest_file} > ${bosh_lite_dir}/deployments/routing-manifest.yml

bosh deployment ${bosh_lite_dir}/deployments/routing-manifest.yml
