#!/bin/bash

set -e

templates=$(dirname $0)/../templates

function usage() {
  >&2 echo "    Usage:
    $0 -c /path/to/cf-release-manifest -d /path/to/diego-release-manifest [-l /path/to/stub1,/path/to/stub2/,...i]

    Ex:
    $0 -c ~/deployments/cf.yml -d ~/deployments/diego.yml -l ~/deployments/stubs/iaas-settings.yml,~/deployments/stubs/instance-count-overrides.yml,~/deployments/stubs/persistent-disk-overrides.yml,~/deployments/stubs/property-overrides.yml
"
  exit 1
}

cf_manifest_file=""
diego_manifest_file=""
stubs=""

while getopts ":hc:d:l:" opt; do
  case "$opt" in
    c)
        cf_manifest_file=$OPTARG
        ;;
    d)
        diego_manifest_file=$OPTARG
        ;;
    l)
        stubs=`echo $OPTARG | tr "," " "`
        ;;
    h)
        usage
        ;;
  esac
done

if [ ! -f "${cf_manifest_file}" ]; then
  >&2 echo "CF release manifest ${cf_manifest_file} does not exist"
  usage
fi

if [ ! -f "${diego_manifest_file}" ]; then
  >&2 echo "Diego release manifest ${diego_manifest_file} does not exist"
  usage
fi

tmpdir=$(mktemp -d /tmp/routing-manifest.XXXXX)
director_uuid=${tmpdir}/director.yml
printf "director_uuid: %s" $(bosh status --uuid) > ${director_uuid}

spiff merge \
  ${templates}/config-from-cf.yml \
  ${templates}/config-from-cf-internal.yml \
  ${cf_manifest_file} \
  > ${tmpdir}/config-from-cf.yml

spiff merge \
  ${templates}/config-from-diego.yml \
  ${templates}/config-from-diego-internal.yml \
  ${diego_manifest_file} \
  > ${tmpdir}/config-from-diego.yml

spiff merge \
  ${templates}/routing.yml \
  ${tmpdir}/config-from-cf.yml \
  ${tmpdir}/config-from-diego.yml \
  $stubs \
  > ${tmpdir}/routing.yml

spiff merge \
  ${templates}/routing-deployment.yml \
  ${director_uuid} \
  ${tmpdir}/routing.yml

