#!/bin/bash

set -e

manifest_generation=$(dirname $0)/../manifest-generation

function usage() {
  >&2 echo "    Usage:
    $0 /path/to/stub/ 

    Ex:
    $0 manifest-generation/bosh-lite-stubs 
"
  exit 1
}

stubs_dir=$1
property_overrides=$stubs_dir/property-overrides.yml
instance_counts=$stubs_dir/instance-count-overrides.yml
persistent_disk=$stubs_dir/persistent-disk-overrides.yml
iaas_settings=$stubs_dir/iaas-settings.yml


if [ ! -z "$2" ]; then
  >&2 echo "Too many arguments"
  usage
fi

if [ ! -f "${property_overrides}" ]; then
  >&2 echo "Did not find Property Overrides stub '${property_overrides}' in '${stubs_dir}' directory"
  usage
fi

if [ ! -f "${instance_counts}" ]; then
  >&2 echo "Did not find Instance Count Overrides stub '${instance_counts}'  in '${stubs_dir}' directory"
  usage
fi

if [ ! -f "${persistent_disk}" ]; then
  >&2 echo "Did not find Persistent Disk Overrides stub '${persistent_disk}'  in '${stubs_dir}' directory"
  usage
fi

if [ ! -f "${iaas_settings}" ]; then
  >&2 echo "Did not find IaaS Setting stub '${iaas_settings}'  in '${stubs_dir}' directory"
  usage
fi

tmpdir=$(mktemp -d /tmp/router-manifest.XXXXX)
director_uuid=${tmpdir}/director.yml
printf "director_uuid: %s" $(bosh status --uuid) > ${director_uuid}

spiff merge \
  ${manifest_generation}/router.yml \
  ${property_overrides} \
  ${instance_counts} \
  ${persistent_disk} \
  ${iaas_settings} \
  > ${tmpdir}/router.yml

  spiff merge \
  ${manifest_generation}/misc-templates/bosh.yml \
  ${director_uuid} \
  ${tmpdir}/router.yml

