#!/bin/bash

absolute_path() {
  (cd $1 && pwd)
}

scripts_path=$(absolute_path `dirname $0`)

ROUTING_RELEASE_DIR=${ROUTING_RELEASE_DIR:-$(absolute_path $scripts_path/..)}
DIEGO_RELEASE_DIR=${DIEGO_RELEASE_DIR:-$(absolute_path $ROUTING_RELEASE_DIR/../diego-release)}
CF_RELEASE_DIR=${CF_RELEASE_DIR:-$(absolute_path $ROUTING_RELEASE_DIR/../cf-release)}

ROUTING_MANIFESTS_DIR=$ROUTING_RELEASE_DIR/bosh-lite/deployments
CF_MANIFESTS_DIR=$CF_RELEASE_DIR/bosh-lite/deployments
DIEGO_MANIFESTS_DIR=$DIEGO_RELEASE_DIR/bosh-lite/deployments

echo ROUTING_RELEASE_DIR=$ROUTING_RELEASE_DIR
echo DIEGO_RELEASE_DIR=$DIEGO_RELEASE_DIR
echo CF_RELEASE_DIR=$CF_RELEASE_DIR

echo ROUTING_MANIFESTS_DIR=$ROUTING_MANIFESTS_DIR
echo CF_MANIFESTS_DIR=$CF_MANIFESTS_DIR
echo DIEGO_MANIFESTS_DIR=$DIEGO_MANIFESTS_DIR
