#!/bin/bash -x

BASEDIR="$(cd $(dirname "$0") && pwd)"
ROUTING_RELEASE_DIR="${BASEDIR}/.."

IMAGE="cloudfoundry/tas-runtime-build"
MOUNT_DIR="/routing-release"
RUN_TEMPLATE_TESTS="cd ${MOUNT_DIR}; source .envrc; scripts/template-tests; echo 'done'"

docker pull "${IMAGE}"
docker run -it \
  -v "${ROUTING_RELEASE_DIR}:${MOUNT_DIR}" \
  "${IMAGE}" \
  /bin/bash -c "${RUN_TEMPLATE_TESTS}"
