#!/bin/bash -x

BASEDIR="$(cd $(dirname "$0") && pwd)"
ROUTING_RELEASE_DIR="${BASEDIR}/.."

# COMPONENT takes only single package name
COMPONENT=$1
PACKAGE=$2
IMAGE="cloudfoundry/tas-runtime-mysql-8.0"
DB="mysql"
MOUNT_DIR="/routing-release"
RUN_UNIT_TESTS="export DB=${DB}; cd ${MOUNT_DIR}; source .envrc; scripts/run-unit-tests ${COMPONENT} ${PACKAGE:-}"

docker pull "${IMAGE}"
docker run -it \
  -v "${ROUTING_RELEASE_DIR}:${MOUNT_DIR}" \
  "${IMAGE}" \
  /bin/bash -c "${RUN_UNIT_TESTS}"
