#!/bin/bash

set -e -x

bin_dir=$(dirname $0)/../bin

tmpdir=$(mktemp -d /tmp/cf-routing-downloads.XXXX)

if uname -a | grep Darwin; then os=darwin; else os=linux; fi
curl -L -o ${tmpdir}/consul-0.6.3.zip "https://releases.hashicorp.com/consul/0.6.3/consul_0.6.3_${os}_amd64.zip"
unzip -o ${tmpdir}/consul-0.6.3.zip -d ./${bin_dir}
rm ${tmpdir}/consul-0.6.3.zip

pushd src/github.com/coreos/etcd
  go install .
popd

export PATH=$PATH:$PWD/bin

if [ -n "$PACKAGE" ]; then
  ginkgo -r -p "$@" "./src/${PACKAGE}"
else
  pushd src/github.com/cloudfoundry-incubator/
    ginkgo -r -keepGoing -p -trace -randomizeAllSpecs -progress \
      uaa-go-client routing-api routing-api-cli cf-tcp-router tcp-emitter "$@"
  popd
fi
