#!/bin/bash
set -ex -o pipefail

BASEDIR="$(dirname "$0")"
PACKAGE="$1"
SUB_PACKAGE="$2"
DB="${DB:-"notset"}"

go version # so we see the version tested in CI

function printStatus {
  local last_exit_status=$?
  set +x
  if (( last_exit_status == 0 )); then
    echo -e '\\nSWEET SUITE SUCCESS'
  else
    echo -e '\\nSUITE FAILURE'
  fi
}
trap printStatus EXIT

"${BASEDIR}/setup-test-environment.sh"
"${BASEDIR}/run-all-component-tests.sh" "${PACKAGE}" "${SUB_PACKAGE}"

