#!/bin/bash

set -e

# ensure gosub is installed (this will recompile it only if necessary)
go get github.com/vito/gosub
go install github.com/vito/gosub

function sync_package() {
  bosh_pkg=${1}

  shift

  (
    set -e

    cd packages/${bosh_pkg}

    {
      cat spec | grep -v '# gosub'

      for package in $(gosub list "$@"); do
        repo=$(echo ${2} | cut -f1-3 -d/)
        if [[ "${repo}" == *"gorouter"* ]]; then
          package="routing-release/src/${package}"
        fi
        echo ${package} | sed -e 's/\(.*\)/  - \1\/*.go # gosub/g'
      done
    } > spec.new

    mv spec.new spec
  )
}

sync_package haproxy-monitor   -app haproxy-monitor/cmd/... &
sync_package router_configurer -app github.com/cloudfoundry-incubator/cf-tcp-router/cmd/... &
sync_package tcp_emitter       -app github.com/cloudfoundry-incubator/tcp-emitter/cmd/... &
sync_package routing-api       -app github.com/cloudfoundry-incubator/routing-api/cmd/... &
sync_package gorouter          -app github.com/cloudfoundry/gorouter/... &
sync_package acceptance_tests \
  -test github.com/cloudfoundry-incubator/routing-acceptance-tests/... \
  -app github.com/onsi/ginkgo/ginkgo &

wait

git diff --name-only packages/*/spec
