#!/bin/bash

if [[ -z ${DB} ]]; then
  DB=mysql
fi

set -eu

THIS_FILE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

"${THIS_FILE_DIR}/docker/container.bash" "${DB}" -d

docker exec routing-release-docker-container '/repo/scripts/docker/build-binaries.bash'
docker exec routing-release-docker-container '/repo/scripts/template-tests'
docker exec routing-release-docker-container '/repo/scripts/docker/test.bash' "$@"
