#!/bin/bash

set -e
set -u
set -o pipefail

# COMPONENT takes only single package name
COMPONENT=${1:-gorouter}
IMAGE="cloudfoundry/cf-routing-pipeline"
MOUNT_DIR="/routing-release"
START_SERVICES="service mysql start && service postgresql start && service rsyslog start"
RUN_UNIT_TEST="cd ${MOUNT_DIR} && source .envrc && ./scripts/run-unit-tests ${COMPONENT}"

docker pull ${IMAGE}
docker run --rm \
  -v "${PWD}:${MOUNT_DIR}" \
  ${IMAGE} \
  /bin/bash -c "${START_SERVICES} && ${RUN_UNIT_TEST}"

