#!/bin/bash
set -ex -o pipefail

BASEDIR="$(dirname "$0")"
PACKAGE="$1"

function printStatus {
  if [[ $? -eq 0 ]]; then
    echo -e '\\nSWEET SUITE SUCCESS'
  else
    echo -e '\\nSUITE FAILURE'
  fi
}
trap printStatus EXIT

${BASEDIR}/setup-test-environment.sh
${BASEDIR}/run-all-component-tests.sh "$PACKAGE"

