#!/bin/bash

IMAGE="cloudfoundry/cf-routing-pipeline"
MOUNT_DIR="/routing-release"
START_SERVICES="service mysql start; service postgresql start"
RUN_UNIT_TEST="cd ${MOUNT_DIR}; source .envrc; ./scripts/run-unit-tests"

docker pull ${IMAGE}
docker run \
  -v "${PWD}:${MOUNT_DIR}" \
  -e DB \
  ${IMAGE} \
  /bin/bash -c "${START_SERVICES};${RUN_UNIT_TEST}"

