#!/bin/bash

set -eu -o pipefail

# if COMPONENT is not specified then all components will be tested
COMPONENT=${1:-""}
IMAGE="cloudfoundry/cf-routing-pipeline"
MOUNT_DIR="/routing-release"
START_SERVICES="chown -R mysql:mysql /var/lib/mysql && service mysql start && service postgresql start && service rsyslog start"
RUN_UNIT_TEST="cd ${MOUNT_DIR} && source .envrc && ./scripts/run-unit-tests ${COMPONENT}"

docker pull ${IMAGE}
docker run --rm \
  -v "${PWD}:${MOUNT_DIR}" \
  ${IMAGE} \
  /bin/bash -c "${START_SERVICES} && ${RUN_UNIT_TEST}"

