#!/bin/bash

set -e

if [[ -z $1 ]]; then
    echo "Must provide cf release manifest"
    exit 1
fi
CF_MANIFEST=$1

echo "WARNING!!: Script redeploys cf-warden with routing-api enabled"

root_dir=$(dirname $0)
bosh_lite_dir=${root_dir}/../bosh-lite
deployment_dir=${bosh_lite_dir}/deployments

mkdir -p $deployment_dir

spiff merge ${CF_MANIFEST} ${bosh_lite_dir}/stubs/cf/* > ${deployment_dir}/cf.yml
bosh -n deployment ${deployment_dir}/cf.yml
bosh -n deploy
