#!/bin/bash

if [ "$1" == "--help" ]; then
  echo "USAGE: $0"
  echo "    This command takes no arguments."
  echo ""
  echo "This script does a git submodule update on all submodules"
  exit 0
fi

set -x

function has_upstream() {
  git rev-parse @{u} > /dev/null 2>&1
}

has_upstream && git pull

# Do not set -e until after has_upstream check so that we always update submodules
set -e

if [[ "$(git --version | grep 'version 1.7')x" != "x" ]]; then
  git submodule foreach --recursive git submodule sync && git submodule update --init --recursive
else
  git submodule sync --recursive && git submodule foreach --recursive git submodule sync  && git submodule update --init --recursive
fi

echo "CF Routing Release has been updated"
