#!/usr/bin/env bash

set -ex

if [[ -f networking-oss-tools/scripts/script_helpers.sh ]]; then
  source networking-oss-tools/scripts/script_helpers.sh
else
  source routing-release-ci/ci/scripts/script_helpers.sh
fi

set +x
  cf_login "${ENVIRONMENT}"
set -x

cf create-isolation-segment "${ISO_SEG_NAME}"
