#!/bin/bash

set -e

LOGFILE="/var/vcap/sys/log/tcp_router/haproxy_reloader.log"

PATH="/var/vcap/packages/tcp_router/bin:/var/vcap/packages/haproxy/bin:$PATH"
DAEMON="$(which haproxy)"
CONFIG=/var/vcap/data/tcp_router/config/haproxy.conf
HAPROXY_PID_FILE=/var/vcap/data/tcp_router/config/haproxy.pid
HAPROXY_SOCKET_FILE=/var/vcap/data/tcp_router/config/haproxy.sock

test -x "${DAEMON}"
test -f "${CONFIG}"

echo "$(date --rfc-3339=ns) starting haproxy_reloader" >> "${LOGFILE}"

"${DAEMON}" -f "${CONFIG}" -p "${HAPROXY_PID_FILE}" -x "${HAPROXY_SOCKET_FILE}" -D -sf "$(cat ${HAPROXY_PID_FILE})" 0<&- &>> "${LOGFILE}"

echo "$(date --rfc-3339=ns) done" >> "${LOGFILE}"
