#!/bin/bash

set -e

RUN_DIR=/var/vcap/sys/run/tcp_router
LOG_DIR=/var/vcap/sys/log/tcp_router
CONFIG_DIR=/var/vcap/jobs/tcp_router/config

function create_directories() {
    mkdir -p $RUN_DIR
    chown -R vcap:vcap $RUN_DIR

    mkdir -p $LOG_DIR
    chown -R vcap:vcap $LOG_DIR
}

function setcap_haproxy() {
    PATH=/var/vcap/packages/haproxy/bin:$PATH
    DAEMON=$(which haproxy)
    setcap cap_net_bind_service,cap_sys_resource=+ep $DAEMON
}

create_directories
setcap_haproxy
chown -R vcap:vcap "${CONFIG_DIR}"

exit 0
