#!/usr/bin/env bash

set -euo pipefail

PIPELINE_DIR="$(dirname $0)/pipelines"

: "${1?"Usage: update <pipeline-name>"}"
PIPELINE_NAME=$1

fly \
  --target routing \
  set-pipeline \
  --pipeline "${PIPELINE_NAME}" \
  --config "${PIPELINE_DIR}/${PIPELINE_NAME}.yml"
