#!/bin/bash
set -xeu

export CONFIG
CONFIG="$PWD/integration-config/${CONFIG_FILE_PATH}"

export GOBIN="$PWD/bin"
export PATH="$GOBIN:$PATH"
mkdir -p $GOBIN

pushd routing-release/src/code.cloudfoundry.org
  go build -o "$GOBIN/ginkgo" github.com/onsi/ginkgo/ginkgo

  packages=("http_routes" "tcp_routing" "smoke_tests")
  for i in "${packages[@]}"
  do
    ginkgo \
      -r "routing-acceptance-tests/$i" "$GINKGO_ARGS" \
      -keepGoing \
      -randomizeAllSpecs \
      -skipPackage=helpers \
      -slowSpecThreshold=120 \
      -nodes="${NODES}"
  done
popd
