#!/bin/bash
set -eu -o pipefail

source networking-oss-deployments/scripts/script_helpers.sh

if [[ -d toolsmiths-metadata-dir ]]; then
  bosh_login_toolsmiths toolsmiths-metadata-dir
elif [[ -d networking-oss-deployments ]]; then
  ENVIRONMENT="${ENVIRONMENT:?"ENVIRONMENT not set"}"
  bosh_login "${ENVIRONMENT}"
else
  echo "Failed to provide either \"toolsmiths-metadata-dir\" or \"networking-oss-deployments\""
  exit 1
fi

function cleanup() {
  pkill ssh || true
}
trap 'cleanup' EXIT

set +x
cmd='sudo chmod a+w /var/vcap/store/syslog_storer/syslog.log; tail -n 100 /var/vcap/store/syslog_storer/syslog.log > /var/vcap/store/syslog_storer/syslog.log'
bosh ssh -c "$cmd" syslog_storer
sleep 60
bosh scp syslog_storer:/var/vcap/store/syslog_storer/syslog.log .
set -x
grep "$(date --utc --date '-1hour' +%Y-%m-%dT%H)\|$(date --utc +%Y-%m-%dT%H)" syslog.log | grep "routing-api" | tee routing-api.log
[ -s routing-api.log ] || (echo "Routing API logs are empty" && exit 1)
grep "$(date --utc --date '-1hour' +%Y-%m-%dT%H)\|$(date --utc +%Y-%m-%dT%H)" syslog.log | grep "gorouter" | tee gorouter.log
[ -s gorouter.log ] || (echo "Gorouter logs are empty" && exit 1)
grep "$(date --utc --date '-1hour' +%Y-%m-%dT%H)\|$(date --utc +%Y-%m-%dT%H)" syslog.log | grep "tcp_router" | tee tcp_router.log
[ -s tcp_router.log ] || (echo "TCP Router logs are empty" && exit 1)
