#!/bin/bash
set -e -x

source ~/.bashrc

echo $TERM
version_tag=$(cat version/version)
export TERM=xterm-256color
echo $TERM

pushd routing-release
  exists=false
  set +e
  git ls-remote --tags | grep $version_tag
  EXIT_STATUS=$?

  if [ "$EXIT_STATUS" == "0" ]; then
    exists=true
    echo "Tag is present"
  fi
  set -e

  if [ $exists = true ]; then
    exit 1
  fi

  set +e
  git diff --quiet
  EXIT_STATUS=$?
  set -e
  if [ "$EXIT_STATUS" -ne "0" ]; then
    echo "There are uncommitted changes! Investigate immediately."
    git status
    exit 1
  fi
popd
