#!/bin/bash
set -ex -o pipefail

source networking-oss-deployments/scripts/script_helpers.sh

if [[ -d toolsmiths-metadata-dir ]]; then
  ENVIRONMENT="$(cat toolsmiths-metadata-dir/name)"
  bosh_login_toolsmiths
else
  ENVIRONMENT="${ENVIRONMENT:?"ENVIRONMENT not set"}"
  bosh_login "${ENVIRONMENT}"
fi

function cleanup() {
  pkill ssh || true
}
trap 'cleanup' EXIT

STEMCELL_PATH=$(ls $STEMCELL_REGEX)

BOSH_DEPLOYMENT="${DEPLOYMENT:-$BOSH_DEPLOYMENT}"

bosh -n us "${STEMCELL_PATH}"

IFS=', ' read -r -a array <<< "${RELEASES_DIR}"

for element in "${array[@]}"
do
  RELEASE_PATH=$(ls $element)
  bosh -n ur "${RELEASE_PATH}"
done

bosh -n -e "${ENVIRONMENT}" deploy "${MANIFEST}"

echo "Running cipher test suite"
bosh run-errand run-cipher-test --keep-alive --download-logs
