#!/bin/bash

set -exu

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

root_dir="${PWD}"
OUTPUT_DIR="${root_dir}/${OUTPUT_DIR:?"OUTPUT_DIR must be provided"}"

export RTR_VERSION=$(cat version/version)

pushd "${CF_ROUTING_RELEASE_DIR}/"

export GOPATH=$PWD
export PATH=$GOPATH/bin:$PATH

	cli_src_dir="src/code.cloudfoundry.org/routing-api-cli"
  rm -rf "${cli_src_dir}"
	cp -r "${root_dir}/routing-api-cli-src" "${cli_src_dir}"

	pushd "${cli_src_dir}"
		./bin/build-all.sh

		pushd out
			tar -vczf rtr-darwin-amd64.tgz rtr-darwin-amd64
			tar -vczf rtr-linux-amd64.tgz rtr-linux-amd64
			echo "===GENERATED BINARIES==="
			CLI_BINARY=$PWD
		popd

		ls out/

	popd
popd

mkdir -p "${OUTPUT_DIR}"

cp -r "${CLI_BINARY}" "${OUTPUT_DIR}"
ls "${OUTPUT_DIR}"
