#!/bin/bash

set -eux
set -o pipefail

source networking-oss-deployments/scripts/script_helpers.sh

bosh_login_toolsmiths

ENV_NAME="$(cat toolsmiths-metadata-dir/name)"
CERT_FILE="$(mktemp)"

set +e
cert="$(openssl s_client \
	-showcerts \
	-connect "any.${ENV_NAME}.cf-app.com:443" \
		</dev/null 2>/dev/null)"
set -e

echo "${cert}" | openssl x509 \
	> "${CERT_FILE}"

credhub set \
	--name "/bosh-${ENV_NAME}/cf/lb_cert" \
	--type certificate \
	--certificate "${CERT_FILE}"
